unit matrices;
interface
uses
  crt,CompoLexico, Listas;
type
 T_TAS = array [ Vprogram..Vopmult, Tid..Tlength] of ^T_LISTA;

Procedure inicializar_matriz(var m:t_TAS);


implementation

Procedure inicializar_matriz(var m:t_TAS);
var
  i,j:TSimboloGramatical;
begin
    for i:=VProgram to Vopmult do
      for j:=Tid to Tlength do
      begin
        m[i,j]:=nil;
      end;
 // program → zafira desc block
 New(m[Vprogram,Tzafira]);
 	 m[Vprogram,Tzafira]^.elementos[1]:=Tzafira;
 	 m[Vprogram,Tzafira]^.elementos[2]:=Vdesc;
 	 m[Vprogram,Tzafira]^.elementos[3]:=Vblock;
 	 m[Vprogram,Tzafira]^.tam:=3;
 // des → id type
 New(m[Vdes,Tid]);
 	 m[Vdes,Tid]^.elementos[1]:=Tid;
 	 m[Vdes,Tid]^.elementos[2]:=Vtype;
 	 m[Vdes,Tid]^.tam:=2;
 // desc → des A
 New(m[Vdesc,Tid]);
 	 m[Vdesc,Tid]^.elementos[1]:=Vdes;
         m[Vdesc,Tid]^.elementos[2]:=VA;
 	 m[Vdesc,Tid]^.tam:=2;
 // A → ; desc A | e
 New(m[VA,Tpunycoma]);
 	 m[VA,Tpunycoma]^.elementos[1]:=Tpunycoma;
 	 m[VA,Tpunycoma]^.elementos[2]:=Vdesc;
         m[VA,Tpunycoma]^.elementos[3]:=VA;
 	 m[VA,Tpunycoma]^.tam:=3;
 New(m[VA,Tstart]);
 	 m[VA,Tstart]^.tam:=0;
 // type → t_real | t_string
 New(m[Vtype,Ttreal]);
 	 m[Vtype,Ttreal]^.elementos[1]:=Ttreal;
 	 m[Vtype,Ttreal]^.tam:=1;
 New(m[Vtype,Ttstring]);
 	 m[Vtype,Ttstring]^.elementos[1]:=Ttstring;
 	 m[Vtype,Ttstring]^.tam:=1;
 // body → sent C
 New(m[Vbody,Tid]);
 	 m[Vbody,Tid]^.elementos[1]:=Vsent;
         m[Vbody,Tid]^.elementos[2]:=VC;
 	 m[Vbody,Tid]^.tam:=2;
 New(m[Vbody,Tinput]);
 	 m[Vbody,Tinput]^.elementos[1]:=Vsent;
 	 m[Vbody,Tinput]^.elementos[2]:=VC;
 	 m[Vbody,Tinput]^.tam:=2;
 New(m[Vbody,Tprint]);
 	 m[Vbody,Tprint]^.elementos[1]:=Vsent;
 	 m[Vbody,Tprint]^.elementos[2]:=VC;
 	 m[Vbody,Tprint]^.tam:=2;
 New(m[Vbody,Twhen]);
 	 m[Vbody,Twhen]^.elementos[1]:=Vsent;
 	 m[Vbody,Twhen]^.elementos[2]:=VC;
 	 m[Vbody,Twhen]^.tam:=2;
 New(m[Vbody,Tduring]);
 	 m[Vbody,Tduring]^.elementos[1]:=Vsent;
 	 m[Vbody,Tduring]^.elementos[2]:=VC;
 	 m[Vbody,Tduring]^.tam:=2;
 // C → sent C | e
 New(m[VC,Tid]);
 	 m[VC,Tid]^.elementos[1]:=Vsent;
 	 m[VC,Tid]^.elementos[2]:=VC;
 	 m[VC,Tid]^.tam:=2;
 New(m[VC,Tinput]);
 	 m[VC,Tinput]^.elementos[1]:=Vsent;
 	 m[VC,Tinput]^.elementos[2]:=VC;
 	 m[VC,Tinput]^.tam:=2;
 New(m[VC,Tprint]);
 	 m[VC,Tprint]^.elementos[1]:=Vsent;
 	 m[VC,Tprint]^.elementos[2]:=VC;
 	 m[VC,Tprint]^.tam:=2;
 New(m[VC,Twhen]);
 	 m[VC,Twhen]^.elementos[1]:=Vsent;
 	 m[VC,Twhen]^.elementos[2]:=VC;
 	 m[VC,Twhen]^.tam:=2;
 New(m[VC,Tduring]);
 	 m[VC,Tduring]^.elementos[1]:=Vsent;
 	 m[VC,Tduring]^.elementos[2]:=VC;
 	 m[VC,Tduring]^.tam:=2;
 New(m[VC,Tend]);
 	 m[VC,Tend]^.tam:=0;
// sent → ...
 New(m[Vsent,Tid]);
 	 m[Vsent,Tid]^.elementos[1]:=Vasig;
         m[Vsent,Tid]^.elementos[2]:=Tpunycoma;
 	 m[Vsent,Tid]^.tam:=2;
 New(m[Vsent,Tinput]);
 	 m[Vsent,Tinput]^.elementos[1]:=Vreading;
         m[Vsent,Tinput]^.elementos[2]:=Tpunycoma;
 	 m[Vsent,Tinput]^.tam:=2;
 New(m[Vsent,Tprint]);
 	 m[Vsent,Tprint]^.elementos[1]:=Vwriting;
         m[Vsent,Tprint]^.elementos[2]:=Tpunycoma;
 	 m[Vsent,Tprint]^.tam:=2;
 New(m[Vsent,Twhen]);
 	 m[Vsent,Twhen]^.elementos[1]:=Vconditional;
         m[Vsent,Twhen]^.elementos[2]:=Tpunycoma;
 	 m[Vsent,Twhen]^.tam:=2;
 New(m[Vsent,Tduring]);
 	 m[Vsent,Tduring]^.elementos[1]:=Vloop;
         m[Vsent,Tduring]^.elementos[2]:=Tpunycoma;
 	 m[Vsent,Tduring]^.tam:=2;
 // asig → id -) xgeneral
 New(m[Vasig,Tid]);
 	 m[Vasig,Tid]^.elementos[1]:=Tid;
 	 m[Vasig,Tid]^.elementos[2]:=Topasig;
 	 m[Vasig,Tid]^.elementos[3]:=Vxgeneral;
 	 m[Vasig,Tid]^.tam:=3;
 // xgeneral → term addterm
 New(m[Vxgeneral,Tsqrt]);
 	 m[Vxgeneral,Tsqrt]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tsqrt]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tsqrt]^.tam:=2;
 New(m[Vxgeneral,Tmenos]);
 	 m[Vxgeneral,Tmenos]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tmenos]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tmenos]^.tam:=2;
 New(m[Vxgeneral,Tid]);
         m[Vxgeneral,Tid]^.elementos[1] := Vterm;
         m[Vxgeneral,Tid]^.elementos[2] := Vaddterm;
         m[Vxgeneral,Tid]^.tam := 2;
 New(m[Vxgeneral,Taparentesis]);
 	 m[Vxgeneral,Taparentesis]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Taparentesis]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Taparentesis]^.tam:=2;
 New(m[Vxgeneral,Tcreal]);
 	 m[Vxgeneral,Tcreal]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tcreal]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tcreal]^.tam:=2;
 New(m[Vxgeneral,Tcstring]);
 	 m[Vxgeneral,Tcstring]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tcstring]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tcstring]^.tam:=2;
 New(m[Vxgeneral,Tsubcad]);
 	 m[Vxgeneral,Tsubcad]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tsubcad]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tsubcad]^.tam:=2;
 New(m[Vxgeneral,Tsearch]);
 	 m[Vxgeneral,Tsearch]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tsearch]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tsearch]^.tam:=2;
 New(m[Vxgeneral,Tlength]);
 	 m[Vxgeneral,Tlength]^.elementos[1]:=Vterm;
 	 m[Vxgeneral,Tlength]^.elementos[2]:=Vaddterm;
 	 m[Vxgeneral,Tlength]^.tam:=2;
 // addterm → opsum term addterm | e
 New(m[Vaddterm,Tmas]);
         m[Vaddterm,Tmas]^.elementos[1]:=Vopsum;
         m[Vaddterm,Tmas]^.elementos[2]:=Vterm;
         m[Vaddterm,Tmas]^.elementos[3]:=Vaddterm;
         m[Vaddterm,Tmas]^.tam :=3;
 New(m[Vaddterm,Tmenos]);
         m[Vaddterm,Tmenos]^.elementos[1]:=Vopsum;
         m[Vaddterm,Tmenos]^.elementos[2]:=Vterm;
         m[Vaddterm,Tmenos]^.elementos[3]:=Vaddterm;
         m[Vaddterm,Tmenos]^.tam :=3;
 New(m[Vaddterm,Tcparentesis]);
 	 m[Vaddterm,Tcparentesis]^.tam:=0;
 New(m[Vaddterm,Tcoma]);
 	 m[Vaddterm,Tcoma]^.tam:=0;
 New(m[Vaddterm,Tpunycoma]);
 	 m[Vaddterm,Tpunycoma]^.tam:=0;
 New(m[Vaddterm,Toprel]);
 	 m[Vaddterm,Toprel]^.tam:=0;
 New(m[Vaddterm,Tand]);
 	 m[Vaddterm,Tand]^.tam:=0;
 New(m[Vaddterm,Tor]);
 	 m[Vaddterm,Tor]^.tam:=0;
 New(m[Vaddterm,Tdo]);
 	 m[Vaddterm,Tdo]^.tam:=0;
 New(m[Vaddterm,Tthen]);
 	 m[Vaddterm,Tthen]^.tam:=0;
 New(m[Vaddterm,Tccorchete]);
 	 m[Vaddterm,Tccorchete]^.tam:=0;
 // term → factor addfactor
 New(m[Vterm,Tid]);
 	 m[Vterm,Tid]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tid]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tid]^.tam:=2;
 New(m[Vterm,Tsqrt]);
 	 m[Vterm,Tsqrt]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tsqrt]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tsqrt]^.tam:=2;
 New(m[Vterm,Tmenos]);
 	 m[Vterm,Tmenos]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tmenos]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tmenos]^.tam:=2;
 New(m[Vterm,Taparentesis]);
 	 m[Vterm,Taparentesis]^.elementos[1]:=Vfactor;
 	 m[Vterm,Taparentesis]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Taparentesis]^.tam:=2;
 New(m[Vterm,Tcreal]);
 	 m[Vterm,Tcreal]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tcreal]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tcreal]^.tam:=2;
 New(m[Vterm,Tcstring]);
 	 m[Vterm,Tcstring]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tcstring]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tcstring]^.tam:=2;
 New(m[Vterm,Tsubcad]);
 	 m[Vterm,Tsubcad]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tsubcad]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tsubcad]^.tam:=2;
 New(m[Vterm,Tsearch]);
 	 m[Vterm,Tsearch]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tsearch]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tsearch]^.tam:=2;
 New(m[Vterm,Tlength]);
 	 m[Vterm,Tlength]^.elementos[1]:=Vfactor;
 	 m[Vterm,Tlength]^.elementos[2]:=Vaddfactor;
 	 m[Vterm,Tlength]^.tam:=2;
 // addfactor → opmult factor addfactor | e
 New(m[Vaddfactor,Tmenos]);
 	 m[Vaddfactor,Tmenos]^.tam:=0;
 New(m[Vaddfactor,Tcparentesis]);
 	 m[Vaddfactor,Tcparentesis]^.tam:=0;
 New(m[Vaddfactor,Tcoma]);
 	 m[Vaddfactor,Tcoma]^.tam:=0;
 New(m[Vaddfactor,Tmas]);
 	 m[Vaddfactor,Tmas]^.tam:=0;
 New(m[Vaddfactor,Toprel]);
         m[Vaddfactor,Toprel]^.tam:=0;
 New(m[Vaddfactor,Tpunycoma]);
         m[Vaddfactor,Tpunycoma]^.tam:=0;
 New(m[Vaddfactor,Tand]);
         m[Vaddfactor,Tand]^.tam:=0;
 New(m[Vaddfactor,Tor]);
         m[Vaddfactor,Tor]^.tam:=0;
 New(m[Vaddfactor,Tdo]);
         m[Vaddfactor,Tdo]^.tam:=0;
 New(m[Vaddfactor,Tthen]);
         m[Vaddfactor,Tthen]^.tam:=0;
 New(m[Vaddfactor,Tccorchete]);
         m[Vaddfactor,Tccorchete]^.tam:=0;
 New(m[Vaddfactor,Tproducto]);
 	 m[Vaddfactor,Tproducto]^.elementos[1]:=Vopmult;
 	 m[Vaddfactor,Tproducto]^.elementos[2]:=Vfactor;
 	 m[Vaddfactor,Tproducto]^.elementos[3]:=Vaddfactor;
 	 m[Vaddfactor,Tproducto]^.tam:=3;
 New(m[Vaddfactor,Tdivision]);
 	 m[Vaddfactor,Tdivision]^.elementos[1]:=Vopmult;
 	 m[Vaddfactor,Tdivision]^.elementos[2]:=Vfactor;
 	 m[Vaddfactor,Tdivision]^.elementos[3]:=Vaddfactor;
 	 m[Vaddfactor,Tdivision]^.tam:=3;
 // factor → base powpart
 New(m[Vfactor,Tid]);
 	 m[Vfactor,Tid]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tid]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tid]^.tam:=2;
 New(m[Vfactor,Tsqrt]);
 	 m[Vfactor,Tsqrt]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tsqrt]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tsqrt]^.tam:=2;
 New(m[Vfactor,Tmenos]);
 	 m[Vfactor,Tmenos]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tmenos]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tmenos]^.tam:=2;
 New(m[Vfactor,Taparentesis]);
 	 m[Vfactor,Taparentesis]^.elementos[1]:=Vbase;
 	 m[Vfactor,Taparentesis]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Taparentesis]^.tam:=2;
 New(m[Vfactor,Tcreal]);
 	 m[Vfactor,Tcreal]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tcreal]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tcreal]^.tam:=2;
 New(m[Vfactor,Tcstring]);
 	 m[Vfactor,Tcstring]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tcstring]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tcstring]^.tam:=2;
 New(m[Vfactor,Tsubcad]);
 	 m[Vfactor,Tsubcad]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tsubcad]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tsubcad]^.tam:=2;
 New(m[Vfactor,Tsearch]);
 	 m[Vfactor,Tsearch]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tsearch]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tsearch]^.tam:=2;
 New(m[Vfactor,Tlength]);
 	 m[Vfactor,Tlength]^.elementos[1]:=Vbase;
 	 m[Vfactor,Tlength]^.elementos[2]:=Vpowpart;
 	 m[Vfactor,Tlength]^.tam:=2;
 // powpart → ^ factor | e
 New(m[Vpowpart,Tpunycoma]);
 	 m[Vpowpart,Tpunycoma]^.tam:=0;
 New(m[Vpowpart,Tmenos]);
 	 m[Vpowpart,Tmenos]^.tam:=0;
 New(m[Vpowpart,Tmas]);
 	 m[Vpowpart,Tmas]^.tam:=0;
 New(m[Vpowpart,Tcoma]);
 	 m[Vpowpart,Tcoma]^.tam:=0;
 New(m[Vpowpart,Toprel]);
 	 m[Vpowpart,Toprel]^.tam:=0;
 New(m[Vpowpart,Tcparentesis]);
 	 m[Vpowpart,Tcparentesis]^.tam:=0;
 New(m[Vpowpart,Tproducto]);
 	 m[Vpowpart,Tproducto]^.tam:=0;
 New(m[Vpowpart,Tdivision]);
 	 m[Vpowpart,Tdivision]^.tam:=0;
 New(m[Vpowpart,Tccorchete]);
         m[Vpowpart,Tccorchete]^.tam := 0;
 New(m[Vpowpart,Tand]);
         m[Vpowpart,Tand]^.tam := 0;
 New(m[Vpowpart,Tor]);
         m[Vpowpart,Tor]^.tam := 0;
 New(m[Vpowpart,Tdo]);
         m[Vpowpart,Tdo]^.tam := 0;
 New(m[Vpowpart,Tthen]);
         m[Vpowpart,Tthen]^.tam := 0;
 New(m[Vpowpart,Tpotencia]);
 	 m[Vpowpart,Tpotencia]^.elementos[1]:=Tpotencia;
 	 m[Vpowpart,Tpotencia]^.elementos[2]:=Vfactor;
 	 m[Vpowpart,Tpotencia]^.tam:=2;
// base → sqrt(xg) | -val | val
 New(m[Vbase,Tsqrt]);
 	 m[Vbase,Tsqrt]^.elementos[1]:=Tsqrt;
 	 m[Vbase,Tsqrt]^.elementos[2]:=Taparentesis;
 	 m[Vbase,Tsqrt]^.elementos[3]:=Vxgeneral;
 	 m[Vbase,Tsqrt]^.elementos[4]:=Tcparentesis;
 	 m[Vbase,Tsqrt]^.tam:=4;
 New(m[Vbase,Tmenos]);
 	 m[Vbase,Tmenos]^.elementos[1]:=Tmenos;
 	 m[Vbase,Tmenos]^.elementos[2]:=Vval;
 	 m[Vbase,Tmenos]^.tam:=2;
 New(m[Vbase,Taparentesis]);
 	 m[Vbase,Taparentesis]^.elementos[1]:=Vval;
 	 m[Vbase,Taparentesis]^.tam:=1;
 New(m[Vbase,Tcreal]);
 	 m[Vbase,Tcreal]^.elementos[1]:=Vval;
 	 m[Vbase,Tcreal]^.tam:=1;
 New(m[Vbase,Tcstring]);
 	 m[Vbase,Tcstring]^.elementos[1]:=Vval;
 	 m[Vbase,Tcstring]^.tam:=1;
 New(m[Vbase,Tsubcad]);
 	 m[Vbase,Tsubcad]^.elementos[1]:=Vval;
 	 m[Vbase,Tsubcad]^.tam:=1;
 New(m[Vbase,Tsearch]);
 	 m[Vbase,Tsearch]^.elementos[1]:=Vval;
 	 m[Vbase,Tsearch]^.tam:=1;
 New(m[Vbase,Tlength]);
 	 m[Vbase,Tlength]^.elementos[1]:=Vval;
 	 m[Vbase,Tlength]^.tam:=1;
 New(m[Vbase,Tid]);
         m[Vbase,Tid]^.elementos[1]:=Vval;
         m[Vbase,Tid]^.tam:=1;
 // val → ...
 New(m[Vval,Tid]);
 	 m[Vval,Tid]^.elementos[1]:=Tid;
 	 m[Vval,Tid]^.tam:=1;
 New(m[Vval,Taparentesis]);
 	 m[Vval,Taparentesis]^.elementos[1]:=Taparentesis;
 	 m[Vval,Taparentesis]^.elementos[2]:=Vxgeneral;
 	 m[Vval,Taparentesis]^.elementos[3]:=Tcparentesis;
 	 m[Vval,Taparentesis]^.tam:=3;
 New(m[Vval,Tcreal]);
 	 m[Vval,Tcreal]^.elementos[1]:=Vconst;
 	 m[Vval,Tcreal]^.tam:=1;
 New(m[Vval,Tcstring]);
 	 m[Vval,Tcstring]^.elementos[1]:=Vconst;
 	 m[Vval,Tcstring]^.tam:=1;
 New(m[Vval,Tsubcad]);
 	 m[Vval,Tsubcad]^.elementos[1]:=Tsubcad;
 	 m[Vval,Tsubcad]^.elementos[2]:=Taparentesis;
 	 m[Vval,Tsubcad]^.elementos[3]:=Vxgeneral;
 	 m[Vval,Tsubcad]^.elementos[4]:=Tcoma;
 	 m[Vval,Tsubcad]^.elementos[5]:=Vxgeneral;
 	 m[Vval,Tsubcad]^.elementos[6]:=Tcoma;
 	 m[Vval,Tsubcad]^.elementos[7]:=Vxgeneral;
 	 m[Vval,Tsubcad]^.elementos[8]:=Tcparentesis;
 	 m[Vval,Tsubcad]^.tam:=8;
 New(m[Vval,Tsearch]);
 	 m[Vval,Tsearch]^.elementos[1]:=Tsearch;
 	 m[Vval,Tsearch]^.elementos[2]:=Taparentesis;
 	 m[Vval,Tsearch]^.elementos[3]:=Vxgeneral;
 	 m[Vval,Tsearch]^.elementos[4]:=Tcoma;
 	 m[Vval,Tsearch]^.elementos[5]:=Vxgeneral;
 	 m[Vval,Tsearch]^.elementos[6]:=Tcparentesis;
 	 m[Vval,Tsearch]^.tam:=6;
 New(m[Vval,Tlength]);
 	 m[Vval,Tlength]^.elementos[1]:=Tlength;
 	 m[Vval,Tlength]^.elementos[2]:=Taparentesis;
 	 m[Vval,Tlength]^.elementos[3]:=Vxgeneral;
 	 m[Vval,Tlength]^.elementos[4]:=Tcparentesis;
 	 m[Vval,Tlength]^.tam:=4;
 // loop → during cond do block
 New(m[Vloop,Tduring]);
 	 m[Vloop,Tduring]^.elementos[1]:=Tduring;
 	 m[Vloop,Tduring]^.elementos[2]:=Vcond;
 	 m[Vloop,Tduring]^.elementos[3]:=Tdo;
 	 m[Vloop,Tduring]^.elementos[4]:=Vblock;
 	 m[Vloop,Tduring]^.tam:=4;
 // block → start body end
 New(m[Vblock,Tstart]);
 	 m[Vblock,Tstart]^.elementos[1]:=Tstart;
 	 m[Vblock,Tstart]^.elementos[2]:=Vbody;
 	 m[Vblock,Tstart]^.elementos[3]:=Tend;
 	 m[Vblock,Tstart]^.tam:=3;
 // cond → cond1 P
 New(m[Vcond,Tacorchete]);
 	 m[Vcond,Tacorchete]^.elementos[1]:=Vcond1;
         m[Vcond,Tacorchete]^.elementos[2]:=VP;
 	 m[Vcond,Tacorchete]^.tam:=2;
 New(m[Vcond,Tnot]);
 	 m[Vcond,Tnot]^.elementos[1]:=Vcond1;
         m[Vcond,Tnot]^.elementos[2]:=VP;
 	 m[Vcond,Tnot]^.tam:=2;
 New(m[Vcond,Tid]);
 	 m[Vcond,Tid]^.elementos[1]:=Vcond1;
         m[Vcond,Tid]^.elementos[2]:=VP;
 	 m[Vcond,Tid]^.tam:=2;
 New(m[Vcond,Tcreal]);
 	 m[Vcond,Tcreal]^.elementos[1]:=Vcond1;
         m[Vcond,Tcreal]^.elementos[2]:=VP;
 	 m[Vcond,Tcreal]^.tam:=2;
 New(m[Vcond,Tcstring]);
 	 m[Vcond,Tcstring]^.elementos[1]:=Vcond1;
         m[Vcond,Tcstring ]^.elementos[2]:=VP;
 	 m[Vcond,Tcstring]^.tam:=2;
 New(m[Vcond,Tsqrt]);
         m[Vcond,Tsqrt]^.elementos[1]:=Vcond1;
         m[Vcond,Tsqrt]^.elementos[2]:=VP;
         m[Vcond,Tsqrt]^.tam := 2;
 New(m[Vcond,Tmenos]);
         m[Vcond,Tmenos]^.elementos[1]:=Vcond1;
         m[Vcond,Tmenos]^.elementos[2]:=VP;
         m[Vcond,Tmenos]^.tam := 2;
 New(m[Vcond,Tsubcad]);
         m[Vcond,Tsubcad]^.elementos[1]:=Vcond1;
         m[Vcond,Tsubcad]^.elementos[2]:=VP;
         m[Vcond,Tsubcad]^.tam := 2;
 New(m[Vcond,Tsearch]);
         m[Vcond,Tsearch]^.elementos[1]:= Vcond1;
         m[Vcond,Tsearch]^.elementos[2]:= VP;
         m[Vcond,Tsearch]^.tam := 2;
 New(m[Vcond,Tlength]);
         m[Vcond,Tlength]^.elementos[1]:=Vcond1;
         m[Vcond,Tlength]^.elementos[2]:=VP;
         m[Vcond,Tlength]^.tam := 2;
 New(m[Vcond,Taparentesis]);
 	 m[Vcond,Taparentesis]^.elementos[1]:=Vcond1;
         m[Vcond,Taparentesis]^.elementos[2]:=VP;
 	 m[Vcond,Taparentesis]^.tam:=2;

 // P →  or cond1 P | e
 New(m[VP,Tor]);
 	 m[VP,Tor]^.elementos[1]:=Tor;
 	 m[VP,Tor]^.elementos[2]:=Vcond1;
             m[VP,Tor]^.elementos[3]:=VP;
 	 m[VP,Tor]^.tam:=3;
 New(m[VP,Tthen]); m[VP,Tthen]^.tam := 0;
 New(m[VP,Tccorchete]);
 	 m[VP,Tccorchete]^.tam:=0;
 New(m[VP,Tdo]);
 	 m[VP,Tdo]^.tam:=0;
 New(m[VP,Tthen]);
 	 m[VP,Tthen]^.tam:=0;

 //  Para cond1 → cond2 B
 New(m[Vcond1,Tnot]);
 	 m[Vcond1,Tnot]^.elementos[1]:=Vcond2;
 	 m[Vcond1,Tnot]^.elementos[2]:=VB;
 	 m[Vcond1,Tnot]^.tam:=2;
 New(m[Vcond1,Tacorchete]);
 	 m[Vcond1,Tacorchete]^.elementos[1]:=Vcond2;
         m[Vcond1,Tacorchete]^.elementos[2]:=VB;
 	 m[Vcond1,Tacorchete]^.tam:=2;
 New(m[Vcond1,Tid]);
 	 m[Vcond1,Tid]^.elementos[1]:=Vcond2;
         m[Vcond1,Tid]^.elementos[2]:=VB;
 	 m[Vcond1,Tid]^.tam:=2;
 New(m[Vcond1,Tcreal]);
 	 m[Vcond1,Tcreal]^.elementos[1]:=Vcond2;
         m[Vcond1,Tcreal]^.elementos[2]:=VB;
 	 m[Vcond1,Tcreal]^.tam:=2;
 New(m[Vcond1,Tcstring]);
 	 m[Vcond1,Tcstring]^.elementos[1]:=Vcond2;
         m[Vcond1,Tcstring]^.elementos[2]:=VB;
 	 m[Vcond1,Tcstring]^.tam:=2;
 New(m[Vcond1,Taparentesis]);
 	 m[Vcond1,Taparentesis]^.elementos[1]:=Vcond2;
         m[Vcond1,Taparentesis]^.elementos[2]:=VB;
 	 m[Vcond1,Taparentesis]^.tam:=2;
 New(m[Vcond1,Tsqrt]);
 	 m[Vcond1,Tsqrt]^.elementos[1]:=Vcond2;
         m[Vcond1,Tsqrt]^.elementos[2]:=VB;
 	 m[Vcond1,Tsqrt]^.tam:=1;
 New(m[Vcond1,Tmenos]);
         m[Vcond1,Tmenos]^.elementos[1]:=Vcond2;
         m[Vcond1,Tmenos]^.elementos[2]:=VB;
         m[Vcond1,Tmenos]^.tam :=2;
 New(m[Vcond1,Tsubcad]);
         m[Vcond1,Tsubcad]^.elementos[1]:=Vcond2;
         m[Vcond1,Tsubcad]^.elementos[2]:=VB;
         m[Vcond1,Tsubcad]^.tam :=2;
 New(m[Vcond1,Tsearch]);
         m[Vcond1,Tsearch]^.elementos[1]:=Vcond2;
         m[Vcond1,Tsearch]^.elementos[2]:=VB;
         m[Vcond1,Tsearch]^.tam :=2;
 New(m[Vcond1,Tlength]);
         m[Vcond1,Tlength]^.elementos[1]:=Vcond2;
         m[Vcond1,Tlength]^.elementos[2]:=VB;
         m[Vcond1,Tlength]^.tam := 2;
// B → and cond2 B | e
 New(m[VB,Tand]);
        m[VB,Tand]^.elementos[1]:=Tand;
        m[VB,Tand]^.elementos[2]:=Vcond2;
        m[VB,Tand]^.elementos[3]:=VB;
        m[VB,Tand]^.tam:=3;
 New(m[VB,Tthen]); m[VB,Tthen]^.tam := 0;
 New(m[VB,Tor]);
        m[VB,Tor]^.tam:=0;
 New(m[VB,Tdo]);
        m[VB,Tdo]^.tam:=0;
 New(m[VB,Tthen]);
        m[VB,Tthen]^.tam:=0;
 New(m[VB,Tccorchete]);
        m[VB,Tccorchete]^.tam:=0;

 // cond2 → not cond2 | cond3
 New(m[Vcond2,Tnot]);
        m[Vcond2,Tnot]^.elementos[1]:=Tnot;
        m[Vcond2,Tnot]^.elementos[2]:=Vcond2;
        m[Vcond2,Tnot]^.tam := 2;
 New(m[Vcond2,Tid]);
        m[Vcond2,Tid]^.elementos[1]:=Vcond3;
        m[Vcond2,Tid]^.tam:=1;
 New(m[Vcond2,Tcreal]);
        m[Vcond2,Tcreal]^.elementos[1]:=Vcond3;
        m[Vcond2,Tcreal]^.tam:=1;
 New(m[Vcond2,Tcstring]);
        m[Vcond2,Tcstring]^.elementos[1]:=Vcond3;
        m[Vcond2,Tcstring]^.tam:=1;
 New(m[Vcond2,Taparentesis]);
        m[Vcond2,Taparentesis]^.elementos[1] := Vcond3;
        m[Vcond2,Taparentesis]^.tam := 1;
 New(m[Vcond2,Tsqrt]);
        m[Vcond2,Tsqrt]^.elementos[1] := Vcond3;
        m[Vcond2,Tsqrt]^.tam := 1;
 New(m[Vcond2,Tmenos]);
        m[Vcond2,Tmenos]^.elementos[1] := Vcond3;
        m[Vcond2,Tmenos]^.tam := 1;
 New(m[Vcond2,Tsubcad]);
        m[Vcond2,Tsubcad]^.elementos[1] := Vcond3;
        m[Vcond2,Tsubcad]^.tam := 1;
 New(m[Vcond2,Tsearch]);
        m[Vcond2,Tsearch]^.elementos[1] := Vcond3;
        m[Vcond2,Tsearch]^.tam := 1;
 New(m[Vcond2,Tlength]);
        m[Vcond2,Tlength]^.elementos[1] := Vcond3;
        m[Vcond2,Tlength]^.tam := 1;
 New(m[Vcond2,Tacorchete]);
        m[Vcond2,Tacorchete]^.elementos[1] := Vcond3;
        m[Vcond2,Tacorchete]^.tam := 1;
 // cond3 → xgeneral oprel xgeneral | [cond]
 New(m[Vcond3,Tid]);
 	 m[Vcond3,Tid]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tid]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tid]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tid]^.tam:=3;
 New(m[Vcond3,Tsqrt]);
 	 m[Vcond3,Tsqrt]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tsqrt]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tsqrt]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tsqrt]^.tam:=3;
 New(m[Vcond3,Tmenos]);
 	 m[Vcond3,Tmenos]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tmenos]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tmenos]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tmenos]^.tam:=3;
 New(m[Vcond3,Tmas]);
 	 m[Vcond3,Tmas]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tmas]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tmas]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tmas]^.tam:=3;
 New(m[Vcond3,Taparentesis]);
 	 m[Vcond3,Taparentesis]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Taparentesis]^.elementos[2]:=Toprel;
 	 m[Vcond3,Taparentesis]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Taparentesis]^.tam:=3;
 New(m[Vcond3,Tcreal]);
 	 m[Vcond3,Tcreal]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tcreal]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tcreal]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tcreal]^.tam:=3;
 New(m[Vcond3,Tcstring]);
 	 m[Vcond3,Tcstring]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tcstring]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tcstring]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tcstring]^.tam:=3;
 New(m[Vcond3,Tsubcad]);
 	 m[Vcond3,Tsubcad]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tsubcad]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tsubcad]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tsubcad]^.tam:=3;
 New(m[Vcond3,Tsearch]);
 	 m[Vcond3,Tsearch]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tsearch]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tsearch]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tsearch]^.tam:=3;
 New(m[Vcond3,Tlength]);
 	 m[Vcond3,Tlength]^.elementos[1]:=Vxgeneral;
 	 m[Vcond3,Tlength]^.elementos[2]:=Toprel;
 	 m[Vcond3,Tlength]^.elementos[3]:=Vxgeneral;
 	 m[Vcond3,Tlength]^.tam:=3;
 New(m[Vcond3,Tacorchete]);
 	 m[Vcond3,Tacorchete]^.elementos[1]:=Tacorchete;
 	 m[Vcond3,Tacorchete]^.elementos[2]:=Vcond;
 	 m[Vcond3,Tacorchete]^.elementos[3]:=Tccorchete;
 	 m[Vcond3,Tacorchete]^.tam:=3;
 // reading → input (c_string , id)
 New(m[Vreading,Tinput]);
 	 m[Vreading,Tinput]^.elementos[1]:=Tinput;
 	 m[Vreading,Tinput]^.elementos[2]:=Taparentesis;
 	 m[Vreading,Tinput]^.elementos[3]:=Tcstring;
 	 m[Vreading,Tinput]^.elementos[4]:=Tcoma;
 	 m[Vreading,Tinput]^.elementos[5]:=Tid;
 	 m[Vreading,Tinput]^.elementos[6]:=Tcparentesis;
 	 m[Vreading,Tinput]^.tam:=6;
 // writing     → print (xgeneral writeitemlist)
 New(m[Vwriting,Tprint]);
 	 m[Vwriting,Tprint]^.elementos[1]:=Tprint;
 	 m[Vwriting,Tprint]^.elementos[2]:=Taparentesis;
 	 m[Vwriting,Tprint]^.elementos[3]:=Vxgeneral;
 	 m[Vwriting,Tprint]^.elementos[4]:=Vwriteitemlist;
 	 m[Vwriting,Tprint]^.elementos[5]:=Tcparentesis;
 	 m[Vwriting,Tprint]^.tam:=5;
 // writeitemlist → , xgeneral writeitemlist | eps
 New(m[Vwriteitemlist,Tcoma]);
         m[Vwriteitemlist,Tcoma]^.elementos[1]:=Tcoma;
         m[Vwriteitemlist,Tcoma]^.elementos[2]:=Vxgeneral;
         m[Vwriteitemlist,Tcoma]^.elementos[3]:=Vwriteitemlist;
         m[Vwriteitemlist,Tcoma]^.tam:=3;
 New(m[Vwriteitemlist,Tcparentesis]);
         m[Vwriteitemlist,Tcparentesis]^.tam:=0;
 // conditional → when cond then block YesOrNoElse
 New(m[Vconditional,Twhen]);
 	 m[Vconditional,Twhen]^.elementos[1]:=Twhen;
 	 m[Vconditional,Twhen]^.elementos[2]:=Vcond;
 	 m[Vconditional,Twhen]^.elementos[3]:=Tthen;
 	 m[Vconditional,Twhen]^.elementos[4]:=Vblock;
 	 m[Vconditional,Twhen]^.elementos[5]:=VYesOrNoElse;
 	 m[Vconditional,Twhen]^.tam:=5;
 // YesOrNoElse → eps | else block
 New(m[VYesOrNoElse,Tpunycoma]);
 	 m[VYesOrNoElse,Tpunycoma]^.tam:=0;
 New(m[VYesOrNoElse,Telse]);
 	 m[VYesOrNoElse,Telse]^.elementos[1]:=Telse;
 	 m[VYesOrNoElse,Telse]^.elementos[2]:=Vblock;
 	 m[VYesOrNoElse,Telse]^.tam:=2;
 New(m[Vconst,Tcreal]);
 	 m[Vconst,Tcreal]^.elementos[1]:=Tcreal;
 	 m[Vconst,Tcreal]^.tam:=1;
 New(m[Vconst,Tcstring]);
 	 m[Vconst,Tcstring]^.elementos[1]:=Tcstring;
 	 m[Vconst,Tcstring]^.tam:=1;
 // opsum → + | -
 New(m[Vopsum,Tmas]);
         m[Vopsum,Tmas]^.elementos[1] := Tmas;
         m[Vopsum,Tmas]^.tam := 1;
 New(m[Vopsum,Tmenos]);
         m[Vopsum,Tmenos]^.elementos[1] := Tmenos;
         m[Vopsum,Tmenos]^.tam := 1;
 //opmult → * | / }
 New(m[Vopmult,Tproducto]);
         m[Vopmult,Tproducto]^.elementos[1] := Tproducto;
         m[Vopmult,Tproducto]^.tam := 1;
 New(m[Vopmult,Tdivision]);
         m[Vopmult,Tdivision]^.elementos[1] := Tdivision;
         m[Vopmult,Tdivision]^.tam := 1;
end;


  end.


